### ISSUE TITLE
YouTube downloads fail

### ISSUE THREAD

**Issue by sjsamdrake** [rishikanthc/Scriberr#224]
Installed via docker on this date (18 Sep 2025). YouTube download doesn't work:

```
Download from YouTube
Enter a YouTube video URL to download its audio for transcription

https://www.youtube.com/watch?v=jv7ozmRzsyI
YouTube thumbnail
Leave empty to use video title
If left empty, the video's title will be used automatically

Failed to download YouTube audio: exit status 1
```

Only entry in the container log:

`[GIN] 2025/09/18 - 19:39:16 | 500 |   75.949576ms |      172.17.0.1 | POST     "/api/v1/transcription/youtube"`

I tried a video that I own and one that showed up in my feed, neither works.

**Comment by sjsamdrake** [comment]
Same issue when installed via brew rather than docker. I verified that "curl"-ing the video URL worked in the same environment.

**Comment by rishikanthc** [comment]
Can you provide more logs ? Would be great if I could get logs from just before you starting the download till the final error. 

Apologies for the bug. I made a lot of changes and might have introduced a regression somewhere.

**Comment by sjsamdrake** [comment]
Unless there's a way to turn on additional logs that was the only entry in the container log for the upload. I was tailing it before during and after the attempt.

**Comment by rishikanthc** [comment]
@sjsamdrake  can you check if yt-dlp was installed on your system

**Comment by sjsamdrake** [comment]
I'm running your container image, and yes it has yt-dip installed.
```
sam@SamLap1:~$ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED      STATUS          PORTS                                       NAMES
4b7f0661b54e   ghcr.io/rishikanthc/scriberr:latest   "docker-entrypoint.s…"   2 days ago   Up 24 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   scriberr
sam@SamLap1:~$ docker exec -it scriberr /bin/bash
root@4b7f0661b54e:/app# find . -name yt\*
./whisperx-env/WhisperX/.venv/bin/yt-dlp
./whisperx-env/WhisperX/.venv/lib/python3.11/site-packages/yt_dlp-2025.9.5.dist-info
./whisperx-env/WhisperX/.venv/lib/python3.11/site-packages/yt_dlp
./whisperx-env/WhisperX/.venv/share/man/man1/yt-dlp.1
./whisperx-env/WhisperX/.venv/share/fish/vendor_completions.d/yt-dlp.fish
./whisperx-env/WhisperX/.venv/share/doc/yt_dlp
./whisperx-env/WhisperX/.venv/share/bash-completion/completions/yt-dlp
root@4b7f0661b54e:/app#
```

**Comment by ballerbude** [comment]
Exact same issue here. Running in docker.

**Comment by rishikanthc** [comment]
Okay so the issue is because YouTube changed something behind the scenes because of which yt-dlp requires a JS runtime. More details can be found in this issue page https://github.com/yt-dlp/yt-dlp/issues/14404

I'll need to update the installation steps. Will look into this.

**Comment by hermannheinrich** [comment]
> Okay so the issue is because YouTube changed something behind the scenes because of which yt-dlp requires a JS runtime. More details can be found in this issue page [yt-dlp/yt-dlp#14404](https://github.com/yt-dlp/yt-dlp/issues/14404)
> 
> I'll need to update the installation steps. Will look into this.

Any updates on this? :-)

**Comment by wahshibinharb** [comment]
any update ?

**Comment by sgtstadanko** [comment]
Can also confirm experiencing same issue. Additionally uploaded mp4 files dont show up or show any processing. All youtube links fail with either the error 1. I also tried just audio only youtube thinking it maybe doesnt process video? Microphone attempts fail as it never prompts or ask for mic permissions from the browser.  here are my logs:

scriberr-scriberr-1  | [GIN] 2025/10/31 - 16:20:21 | 500 |  105.892995ms |   192.168.1.132 | POST     "/api/v1/transcription/youtube"
scriberr-scriberr-1  | [GIN] 2025/10/31 - 16:20:23 | 500 |   99.179414ms |   192.168.1.132 | POST     "/api/v1/transcription/youtube"
scriberr-scriberr-1  | [GIN] 2025/10/31 - 16:20:24 | 500 |  105.001227ms |   192.168.1.132 | POST     "/api/v1/transcription/youtube"


Using GPU docker-compose from docs:


cat docker-compose.yml 

version: "3.9"
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:v1.0.4-cuda
    ports:
      - "8081:8080"
    volumes:
      - /opt/scriberr:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  scriberr_data: {}

**Comment by Ixian** [comment]
I got it working, submitted PR https://github.com/rishikanthc/Scriberr/pull/259
There's a couple other bugfixes around the UV environment I found and fixed that I can submit as well. However the "main" branch of this repo is ahead of the pre-compliled docker image release so I'm not certain where the author is at with this project.

**Comment by sjsamdrake** [comment]
Great that it's fixed. When might the fix make it into the :latest container image?

**Comment by rishikanthc** [comment]
Should be sometime this weekend. Finalizing a few PRs and cleaning up things. I should be able to push out the next release by this weekend. 
Apologies for the slowdown. It's been quite hectic.

**Comment by sjsamdrake** [comment]
Sorry to be buggy, just wondering what the status of this release is? Thanks!

**Comment by rishikanthc** [comment]
@sjsamdrake no worries.. and apologies for the delay.. quite a few people have been asking me about the status.. xD
I'm almost there.. Here's my to-do list for the release:
- add unzip dependency installation to Dockerfile.cuda
- update homebrew CI/CD pipeline to install required dependencies
- update readme (docs)
- instructions for migrating from v1.1.0 to v1.2.0 (docs)
- update installation instructions (docs)
- fix screenshots not loading in https://scriberr.app/docs/usage (docs)
- Cleanup unused config variables

It's all minor things (mostly documentation chore) that I need to complete. The new documentation site is already up at https://scriberr.app 
I just want to ensure all documentation is in place as the last time there were issues with lack of/bad documentation.. 
I apologize for the delay.. I know I have been pushing the release for the last 2 weeks, but I'll release it today. I promise.
Should be out sometime today evening. I'm surprised at the enthusiasm that users have shown towards the next release and it makes me happy.. I apologize for the delays.. Since this release adds a bunch of new features and changes, I want to ensure everything is documented.

**Comment by rishikanthc** [comment]
@sjsamdrake hey !! I have pushed the docker images for the new release.
I couldn't get to updating the docs (readme) and website.. You can try out the images.. The docker-compose files on the main branch are up to date and should help you get started in no time. If you are migrating from v1.1.0 make sure to delete the whisperx-env folder completely. v1.2.0 separates the data and the env and both can persist on a mounted volume to avoid having to redownload models at each restart.
Make sure to use the v1.2.0 tag as latest hasn't been set yet.. Cuda image is available as well.
I'll make the official release first thing tomorrow morning. Sorry.. I really tried to wrap it up but ran out of time.

**Comment by rishikanthc** [comment]
@sjsamdrake Hey ! I dunno if you saw, the new release is out. I released it yesterday. Please do try it out and let me know your thoughts

**Comment by sjsamdrake** [comment]
Sorry for the delay, just getting back to this. Still fails using  the current docker compose CPU setup.

Told to transcribe youtube video https://www.youtube.com/watch?v=2psXxetNpoo (chosen randomly) the GUI says:

Failed to downlad YouTube audio: exit status 1. 

Log:

```
INFO  23:30:35 GET /api/v1/profiles/ 200 0.53ms
INFO  23:30:35 GET /api/v1/transcription/list?page=1&limit=20&sort_by=created_at&sort_order=desc 200 0.92ms
time=23:30:47 level="INFO " msg="YouTube title retrieved" title="I Couldn't Wait! I Made My Own DREAM Steam Machine" duration=2.927100836s
time=23:30:47 level="INFO " msg="Starting YouTube download" url="https://www.youtube.com/watch?v=2psXxetNpoo" job_id=cc655c6b-faa6-4b07-a660-ac9953657ca8
time=23:30:50 level=ERROR msg="YouTube download failed" url="https://www.youtube.com/watch?v=2psXxetNpoo" job_id=cc655c6b-faa6-4b07-a660-ac9953657ca8 error="exit status 1" stderr="WARNING: [youtube] 2psXxetNpoo: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details\nERROR: unable to download video data: HTTP Error 403: Forbidden\n" duration=3.008056681s
INFO  23:30:50 POST /api/v1/transcription/youtube 500 5935.75ms
```

This is with the CPU docker compose file from https://github.com/rishikanthc/Scriberr:


```
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:v1.2.0
    ports:
      - "8080:8080"
    volumes:
      - scriberr_data:/app/data # volume for data
      - env_data:/app/whisperx-env # volume for models and python envs
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - APP_ENV=production # DO NOT CHANGE THIS
      # CORS: comma-separated list of allowed origins for production
      # - ALLOWED_ORIGINS=https://your-domain.com
      # - SECURE_COOKIES=false # Uncomment this ONLY if you are not using SSL
    restart: unless-stopped

volumes:
  scriberr_data: {}
  env_data: {}
```

Full log from startup:

```
sam@fd1:~/scriberr$ sudo docker logs scriberr-scriberr-1 -f
=== Scriberr Container Setup ===
Requested UID: 1000, GID: 1000
Using default user (UID=1000, GID=1000)
Setting up data directories...
=== Setup Complete ===
Switching to user appuser (UID=1000, GID=1000) and starting application...
time=22:45:52 level="INFO " msg="Starting Scriberr" version=dev
[+] Loading configuration
time=22:45:52 level="INFO " msg="Registering adapters with environment path" whisperx_env=/app/whisperx-env
time=22:45:52 level="INFO " msg="Adapter registration complete"
[+] Connecting to database
[+] Setting up authentication
[+] Initializing SSE broadcaster
[+] Initializing repositories
[+] Initializing services
[+] Initializing transcription service
[+] Initializing transcription service
[+] Preparing Python environment
time=22:45:52 level="INFO " msg="Initializing unified transcription service"
time=22:45:52 level="INFO " msg="Initializing registered models in parallel..."
time=22:45:52 level="INFO " msg="Preparing NVIDIA Sortformer environment" env_path=/app/whisperx-env/parakeet
time=22:45:52 level="INFO " msg="Preparing NVIDIA Parakeet environment" env_path=/app/whisperx-env/parakeet
time=22:45:52 level="INFO " msg="transcription model initialized" model_id=openai_whisper
time=22:45:52 level="INFO " msg="Preparing NVIDIA Canary environment" env_path=/app/whisperx-env/parakeet
time=22:45:52 level="INFO " msg="Preparing PyAnnote environment" env_path=/app/whisperx-env/pyannote
time=22:45:52 level="INFO " msg="Preparing WhisperX environment" env_path=/app/whisperx-env
time=22:45:52 level="INFO " msg="Parakeet environment not ready, setting up"
time=22:45:52 level="INFO " msg="Installing Parakeet dependencies"
time=22:45:52 level="INFO " msg="Environment already configured by Parakeet"
time=22:45:52 level="INFO " msg="Downloading Canary model" path=/app/whisperx-env/parakeet/canary-1b-v2.nemo
time=22:45:52 level="INFO " msg="Downloading Sortformer model" path=/app/whisperx-env/parakeet/diar_streaming_sortformer_4spk-v2.nemo
Downloading diar_streaming_sortformer_4spk-v2.nemo: 100% (449.5 MB / 449.5 MB)
time=22:46:03 level="INFO " msg="Successfully downloaded Sortformer model" size=471367680
time=22:46:03 level="INFO " msg="Sortformer environment prepared successfully"
time=22:46:03 level="INFO " msg="diarization model initialized" model_id=sortformer
Downloading canary-1b-v2.nemo: 100% (5.9 GB / 5.9 GB)
time=22:47:34 level="INFO " msg="Successfully downloaded Canary model" size=6358958080
time=22:47:34 level="INFO " msg="Canary environment prepared successfully"
time=22:47:34 level="INFO " msg="transcription model initialized" model_id=canary
time=22:59:02 level="INFO " msg="WhisperX environment already ready"
time=22:59:02 level="INFO " msg="transcription model initialized" model_id=whisperx
time=23:01:00 level="INFO " msg="PyAnnote already available in environment"
time=23:01:00 level="INFO " msg="diarization model initialized" model_id=pyannote
time=23:04:12 level="INFO " msg="Downloading Parakeet model" path=/app/whisperx-env/parakeet/parakeet-tdt-0.6b-v3.nemo
Downloading parakeet-tdt-0.6b-v3.nemo: 100% (2.3 GB / 2.3 GB)
time=23:04:52 level="INFO " msg="Successfully downloaded Parakeet model" size=2509332480
time=23:04:52 level="INFO " msg="Created buffered transcription script" path=/app/whisperx-env/parakeet/transcribe_buffered.py
time=23:04:52 level="INFO " msg="Parakeet environment prepared successfully"
time=23:04:52 level="INFO " msg="transcription model initialized" model_id=parakeet
time=23:04:52 level="INFO " msg="Model initialization completed"
time=23:04:52 level="INFO " msg="Unified transcription service initialized successfully"
[+] Initializing quick transcription service
[+] Starting background processing
time=23:04:52 level="INFO " msg="Scriberr is ready" url=http://0.0.0.0:8080
INFO  23:27:51 GET / 200 13.92ms
INFO  23:27:54 GET / 200 0.04ms
INFO  23:27:54 GET /registerSW.js 200 0.03ms
INFO  23:27:54 GET /assets/react-vendor-gH-7aFTg.js 200 0.16ms
INFO  23:27:54 GET /assets/lucide-vendor-DqOzg3lk.js 200 0.09ms
INFO  23:27:54 GET /assets/index-C_Z9Hy0w.css 200 0.22ms
INFO  23:27:54 GET /assets/index-IrmjfxMB.js 200 0.29ms
INFO  23:27:54 GET /assets/ui-vendor-CDXM-yxm.js 200 0.16ms
INFO  23:27:55 GET /api/v1/auth/registration-status 200 1.20ms
INFO  23:27:55 GET /manifest.webmanifest 200 0.05ms
INFO  23:27:55 GET /favicon.svg 200 0.03ms
INFO  23:27:55 GET /sw.js 200 0.02ms
INFO  23:27:55 GET /icon512_rounded.png 200 0.19ms
INFO  23:27:55 GET /workbox-8c29f6e4.js 200 0.15ms
INFO  23:27:55 GET /registerSW.js 200 0.02ms
INFO  23:27:55 GET /index.html 200 0.01ms
INFO  23:27:55 GET /assets/use-mobile-L57QX8pc.js 200 0.01ms
INFO  23:27:55 GET /assets/ui-vendor-CDXM-yxm.js 200 0.09ms
INFO  23:27:55 GET /assets/table-vendor-DxkQxFe9.js 200 0.01ms
INFO  23:27:55 GET /assets/switch-CAc8qj7z.js 200 0.03ms
INFO  23:27:55 GET /assets/react-vendor-gH-7aFTg.js 200 0.04ms
INFO  23:27:55 GET /assets/popover-6ZIWJK8v.js 200 0.01ms
INFO  23:27:55 GET /assets/markdown-vendor-C_Y9hXhv.js 200 0.36ms
INFO  23:27:55 GET /assets/lucide-vendor-DqOzg3lk.js 200 0.08ms
INFO  23:27:55 GET /assets/index-IrmjfxMB.js 200 0.56ms
INFO  23:27:55 GET /assets/index-C_Z9Hy0w.css 200 0.08ms
INFO  23:27:55 GET /assets/TranscriptionConfigDialog-Bt7b0h3N.js 200 0.10ms
INFO  23:27:55 GET /assets/SettingsPage-CIkREj6h.js 200 0.06ms
INFO  23:27:55 GET /assets/Layout-BsWiOIBR.js 200 0.01ms
INFO  23:27:55 GET /assets/Header-DefQj_rF.js 200 0.43ms
INFO  23:27:55 GET /assets/Dashboard-BZwO2dHc.js 200 0.09ms
INFO  23:27:55 GET /assets/CLISettingsPage-C_HIP4xx.js 200 0.05ms
INFO  23:27:55 GET /assets/CLIAuthConfirmation-B2xjMuzd.js 200 0.01ms
INFO  23:27:55 GET /assets/AudioDetailView-B2r2ek4m.js 200 0.06ms
INFO  23:27:55 GET /icon512_maskable.png 200 0.14ms
INFO  23:27:55 GET /icon512_rounded.png 200 0.10ms
INFO  23:27:55 GET /manifest.webmanifest 200 0.01ms
INFO  23:28:10 POST /api/v1/auth/register 201 87.85ms
INFO  23:28:11 GET /api/v1/profiles/ 200 0.65ms
INFO  23:28:11 GET /api/v1/transcription/list?page=1&limit=20&sort_by=created_at&sort_order=desc 200 1.47ms
INFO  23:30:35 GET /api/v1/profiles/ 200 0.53ms
INFO  23:30:35 GET /api/v1/transcription/list?page=1&limit=20&sort_by=created_at&sort_order=desc 200 0.92ms
time=23:30:47 level="INFO " msg="YouTube title retrieved" title="I Couldn't Wait! I Made My Own DREAM Steam Machine" duration=2.927100836s
time=23:30:47 level="INFO " msg="Starting YouTube download" url="https://www.youtube.com/watch?v=2psXxetNpoo" job_id=cc655c6b-faa6-4b07-a660-ac9953657ca8
time=23:30:50 level=ERROR msg="YouTube download failed" url="https://www.youtube.com/watch?v=2psXxetNpoo" job_id=cc655c6b-faa6-4b07-a660-ac9953657ca8 error="exit status 1" stderr="WARNING: [youtube] 2psXxetNpoo: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details\nERROR: unable to download video data: HTTP Error 403: Forbidden\n" duration=3.008056681s
INFO  23:30:50 POST /api/v1/transcription/youtube 500 5935.75ms
```
