### ISSUE TITLE
"Unable to load audio stream"

### ISSUE THREAD

**Issue by stony007de** [rishikanthc/Scriberr#316]
Now the full log with the correct error!
I upload a wav or a m4a audiofile and try to trancribe. After a short while there is a error "! Unable to load audio stream."

the docker log shows.
```
2025/12/18 21:06:20 /src/internal/repository/implementations.go:178 record not found
[0.805ms] [rows:0] SELECT * FROM `transcription_job_executions` WHERE transcription_job_id = "bd7373ba-3fa4-45e2-a395-00b431e84581" AND status = "completed" ORDER BY created_at DESC,`transcription_job_executions`.`id` LIMIT 1
INFO  21:06:20 GET /api/v1/transcription/bd7373ba-3fa4-45e2-a395-00b431e84581/execution 200 2.66ms
INFO  21:06:20 GET /api/v1/transcription/bd7373ba-3fa4-45e2-a395-00b431e84581 200 1.59ms
INFO  21:06:20 GET /api/v1/transcription/bd7373ba-3fa4-45e2-a395-00b431e84581/audio 401 0.06ms
INFO  21:06:20 GET /api/v1/transcription/bd7373ba-3fa4-45e2-a395-00b431e84581/speakers 200 1.07ms

2025/12/18 21:06:20 /src/internal/repository/implementations.go:353 record not found
[0.130ms] [rows:0] SELECT * FROM `summaries` WHERE transcription_id = "bd7373ba-3fa4-45e2-a395-00b431e84581" ORDER BY created_at DESC,`summaries`.`id` LIMIT 1
INFO  21:06:20 GET /api/v1/transcription/bd7373ba-3fa4-45e2-a395-00b431e84581/summary 200 0.55ms
INFO  21:06:20 GET /api/v1/transcription/bd7373ba-3fa4-45e2-a395-00b431e84581/transcript 200 1.29ms
time=21:06:22 level=ERROR msg="WhisperX execution failed" error="exit status 1"
time=21:06:22 level="INFO " msg="Model processing completed" model_id=whisperx job_id=bd7373ba-3fa4-45e2-a395-00b431e84581 processing_time=12.168703139s
time=21:06:22 level=ERROR msg="Job processing failed" worker_id=0 job_id=bd7373ba-3fa4-45e2-a395-00b431e84581 error="single-track processing failed: transcription failed: WhisperX execution failed: exit status 1\nLogs:\nDownloading nvidia-cudnn-cu12 (674.0MiB)\nDownloading nvidia-cusparselt-cu12 (273.9MiB)\nDownloading nvidia-cublas-cu12 (374.9MiB)\nDownloading nvidia-nccl-cu12 (307.4MiB)\n  × Failed to download `nvidia-cusparselt-cu12==0.7.1`\n  ├─▶ Failed to extract archive:\n  │   nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl\n  ├─▶ I/O operation failed during extraction\n  ╰─▶ failed to create directory\n      `/home/appuser/.cache/uv/.tmpCXnsQw/nvidia_cusparselt_cu12-0.7.1.dist-info`:\n      No space left on device (os error 28)\n  help: `nvidia-cusparselt-cu12` (v0.7.1) was included because `whisperx`\n        (v3.7.4) depends on `torch` (v2.8.0+cu126) which depends on\n        `nvidia-cusparselt-cu12`\n"
INFO  21:06:22 GET /api/v1/profiles/ 200 2.34ms
INFO  21:06:22 GET /api/v1/transcription/list?page=1&limit=20&sort_by=created_at&sort_order=desc 200 3.03ms
INFO  21:06:22 GET /api/v1/events/?job_id=bd7373ba-3fa4-45e2-a395-00b431e84581 200 37.96ms
```

my Profile settings are:

Model Family: **Whisper**
Module Size: **Small** 
Language: **German**
Task: **Transcribe**
Device: **CPU**
Rest is not configured.

**Comment by rishikanthc** [comment]
So the unable to load audio on the frontend is an expired cookie error. Simply logout and login again so it gets the new cookies. 

Regarding the actual transaction error, did you set the permissions for the env directory as well ? The instructions I gave you for the database error ? You need to do the same for the env folder as well.

**Comment by rishikanthc** [comment]
So the unable to load audio stream is a frontend error. It's most likely using stale cookies from the previous instance you were running. So to refresh the auth tokens and get new tokens you logout and login. That should fix it. 


The actual transcription error is because of permissions. Your logs say out of memory error. So you need to set permissions for the env directory / volume as well just like the instructions I gave you for the data directory 

Edit: if you set permissions correctly and still get the out of space error you might be running out of disk space xD the models are quite large (several GBs) so make sure you have sufficient disk space.

**Comment by storrington** [comment]
I've been having this problem too connecting with HTTP, logging out/in or clearing cookies didn't fix it.

Setup a reverse proxy to get a HTTPS connection with a valid certificate and it now shows the audio. Guessing it would work without a valid certificate too.

**Comment by rishikanthc** [comment]
If you're connecting via http without SSL you need to set SECURE_COOKIES=false in compose. @storrington it should work then.

**Comment by rishikanthc** [comment]
Updated docs for this: https://scriberr.app/docs/troubleshooting

Closing the issue. If you are still having trouble with this please feel free to reopen the issue.

**Comment by stony007de** [comment]
Reinstalled with other hardware sizing and it works!!

Thank you..
